// <auto-generated />
using System;
using Handball_Shopv1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Handball_Shopv1.Server.Migrations
{
    [DbContext(typeof(Data_ctx))]
    [Migration("20230818220900_Additions2")]
    partial class Additions2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Handball_Shopv1.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "basketball",
                            Name = "Equipment",
                            Url = "equipment"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "tshirt",
                            Name = "Sportswear",
                            Url = "clothes"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "shoe-prints",
                            Name = "Footwear",
                            Url = "Footwear"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "headphones",
                            Name = "Accessories",
                            Url = "accessories"
                        });
                });

            modelBuilder.Entity("Handball_Shopv1.Shared.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 9,
                            Name = "White"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gray"
                        });
                });

            modelBuilder.Entity("Handball_Shopv1.Shared.Platfrom_size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platfroms_size");
                });

            modelBuilder.Entity("Handball_Shopv1.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ColorOfPreview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Demensions")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Quality")
                        .HasColumnType("int");

                    b.Property<string>("SizeOfPreview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A sticky substance applied to the hands or ball to help provide grip when catching a ball",
                            Image = "https://contents.mediadecathlon.com/p974581/k$5043e312a6d703b0fbbeee605bb2c18e/handball-200-ml-resin-white.jpg?&f=800x800",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 5.0,
                            Price = 5.5499999999999998,
                            Title = "Resin"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A ball used in the sport of handball, the ball comes in different sizes ranging from 1 to 3 where 1 is for individuals aged below 9, where 2 is for 9-16, and 3 is for ages 16+",
                            Image = "https://th.bing.com/th/id/OIP.MWZvNTIlLKSKX-GA1fxD1wHaJ2?w=149&h=195&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 17.0,
                            Price = 20.0,
                            SizeOfPreview = "2",
                            Title = "Handball"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-quality goalkeeper gloves designed for handball.",
                            Image = "https://www.ushandball.org/wp-content/uploads/2020/04/55_202_edge-red-500x500-1.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 40.0,
                            Price = 32.990000000000002,
                            SizeOfPreview = "M",
                            Title = "Handball Goalkeeper Gloves"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Set of 10 training cones for handball drills and agility exercises.",
                            Image = "https://th.bing.com/th/id/OIP.fmooRuaDr8s4PgXttfwTrwHaHa?w=196&h=196&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 15.0,
                            Price = 12.5,
                            Title = "Handball Training Cones"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Official handball jersey for players and fans.",
                            Image = "https://th.bing.com/th/id/OIP.-o6S2LWJvZpQfGlN06hm2gHaHa?w=182&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 30.0,
                            Price = 25.989999999999998,
                            SizeOfPreview = "XL",
                            Title = "Handball Jersey"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sturdy handball goal for indoor and outdoor use.",
                            Image = "https://th.bing.com/th/id/OIP.MPaYi-lsGE9Ls6TI6vJK7QHaHa?w=198&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 120.0,
                            Price = 99.989999999999995,
                            SizeOfPreview = "Standard",
                            Title = "Handball Goal"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Specialized court shoes with excellent grip for handball.",
                            Image = "https://th.bing.com/th/id/OIP.F_JVGxVV3o9j4G4xMMIl2AHaHa?w=184&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 90.0,
                            Price = 74.989999999999995,
                            SizeOfPreview = "US 11",
                            Title = "Handball Court Shoes"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            ColorOfPreview = "Black",
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Absorbent wristband for handball players to wipe away sweat.",
                            Image = "https://th.bing.com/th/id/OIP.Hj1oxc9FtHsW9fMmVKtjsgHaFT?w=250&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 8.0,
                            Price = 6.5,
                            Title = "Handball Wristband"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cushioned socks for maximum comfort during handball matches.",
                            Image = "https://th.bing.com/th/id/OIP.UJClor0v7As5z6cIXXyk9QHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 12.0,
                            Price = 9.9900000000000002,
                            SizeOfPreview = "UK 8-10",
                            Title = "Handball Court Socks"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ColorOfPreview = "Black",
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweat-absorbent headband to keep hair and sweat away during handball games.",
                            Image = "https://th.bing.com/th/id/OIP.gnTH3x7XoeTS3TWwKZzZKAHaHa?w=202&h=202&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 10.0,
                            Price = 7.9900000000000002,
                            Title = "Handball Headband"
                        });
                });

            modelBuilder.Entity("PlatformProduct", b =>
                {
                    b.Property<int>("PlatformsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("PlatformsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("PlatformProduct");

                    b.HasData(
                        new
                        {
                            PlatformsId = 1,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 2,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 3,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 4,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 5,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 6,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 7,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 8,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 9,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 10,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 11,
                            ProductsId = 8
                        },
                        new
                        {
                            PlatformsId = 1,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 2,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 3,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 4,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 5,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 6,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 7,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 8,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 9,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 10,
                            ProductsId = 10
                        },
                        new
                        {
                            PlatformsId = 11,
                            ProductsId = 10
                        });
                });

            modelBuilder.Entity("Platfrom_sizeProduct", b =>
                {
                    b.Property<int>("Platforms_sizeId")
                        .HasColumnType("int");

                    b.Property<int>("Products_Id")
                        .HasColumnType("int");

                    b.HasKey("Platforms_sizeId", "Products_Id");

                    b.HasIndex("Products_Id");

                    b.ToTable("Platfrom_sizeProduct");
                });

            modelBuilder.Entity("PlatformProduct", b =>
                {
                    b.HasOne("Handball_Shopv1.Shared.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Handball_Shopv1.Shared.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Platfrom_sizeProduct", b =>
                {
                    b.HasOne("Handball_Shopv1.Shared.Platfrom_size", null)
                        .WithMany()
                        .HasForeignKey("Platforms_sizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Handball_Shopv1.Shared.Product", null)
                        .WithMany()
                        .HasForeignKey("Products_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
