// <auto-generated />
using System;
using Handball_Shopv1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Handball_Shopv1.Server.Migrations
{
    [DbContext(typeof(Data_ctx))]
    partial class Data_ctxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Handball_Shopv1.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "basketball",
                            Name = "Equipment",
                            Url = "equipment"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "tshirt",
                            Name = "Sportswear",
                            Url = "clothes"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "shoe-prints",
                            Name = "Footwear",
                            Url = "Footwear"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "headphones",
                            Name = "Accessories",
                            Url = "accessories"
                        });
                });

            modelBuilder.Entity("Handball_Shopv1.Shared.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platforms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "XS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "S"
                        },
                        new
                        {
                            Id = 3,
                            Name = "M"
                        },
                        new
                        {
                            Id = 4,
                            Name = "L"
                        },
                        new
                        {
                            Id = 5,
                            Name = "XL"
                        },
                        new
                        {
                            Id = 6,
                            Name = "1"
                        },
                        new
                        {
                            Id = 7,
                            Name = "2"
                        },
                        new
                        {
                            Id = 8,
                            Name = "3"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("Handball_Shopv1.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ColorOfPreview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Demensions")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int?>("Quality")
                        .HasColumnType("int");

                    b.Property<string>("SizeOfPreview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A sticky substance applied to the hands or ball to help provide grip when catching a ball",
                            Image = "https://contents.mediadecathlon.com/p974581/k$5043e312a6d703b0fbbeee605bb2c18e/handball-200-ml-resin-white.jpg?&f=800x800",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Resin"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A ball used in the sport of handball, the ball comes in different sizes ranging from 1 to 3 where 1 is for individuals aged below 9, where 2 is for 9-16, and 3 is for ages 16+",
                            Image = "https://th.bing.com/th/id/OIP.MWZvNTIlLKSKX-GA1fxD1wHaJ2?w=149&h=195&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            SizeOfPreview = "2",
                            Title = "Handball"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-quality goalkeeper gloves designed for handball.",
                            Image = "https://www.ushandball.org/wp-content/uploads/2020/04/55_202_edge-red-500x500-1.png",
                            IsDeleted = false,
                            IsPublic = false,
                            SizeOfPreview = "M",
                            Title = "Handball Goalkeeper Gloves"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Set of 10 training cones for handball drills and agility exercises.",
                            Image = "https://th.bing.com/th/id/OIP.fmooRuaDr8s4PgXttfwTrwHaHa?w=196&h=196&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Handball Training Cones"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Official handball jersey for players and fans.",
                            Image = "https://th.bing.com/th/id/OIP.-o6S2LWJvZpQfGlN06hm2gHaHa?w=182&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            SizeOfPreview = "XL",
                            Title = "Handball Jersey"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sturdy handball goal for indoor and outdoor use.",
                            Image = "https://th.bing.com/th/id/OIP.MPaYi-lsGE9Ls6TI6vJK7QHaHa?w=198&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            SizeOfPreview = "Standard",
                            Title = "Handball Goal"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Specialized court shoes with excellent grip for handball.",
                            Image = "https://th.bing.com/th/id/OIP.F_JVGxVV3o9j4G4xMMIl2AHaHa?w=184&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            SizeOfPreview = "US 11",
                            Title = "Handball Court Shoes"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            ColorOfPreview = "Black",
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Absorbent wristband for handball players to wipe away sweat.",
                            Image = "https://th.bing.com/th/id/OIP.Hj1oxc9FtHsW9fMmVKtjsgHaFT?w=250&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Handball Wristband"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cushioned socks for maximum comfort during handball matches.",
                            Image = "https://th.bing.com/th/id/OIP.UJClor0v7As5z6cIXXyk9QHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            SizeOfPreview = "UK 8-10",
                            Title = "Handball Court Socks"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ColorOfPreview = "Black",
                            DateCreated = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweat-absorbent headband to keep hair and sweat away during handball games.",
                            Image = "https://th.bing.com/th/id/OIP.gnTH3x7XoeTS3TWwKZzZKAHaHa?w=202&h=202&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Handball Headband"
                        });
                });

            modelBuilder.Entity("Handball_Shopv1.Shared.Variants_Product", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("AdditionId")
                        .HasColumnType("int");

                    b.Property<double?>("OriginalPrice")
                        .HasColumnType("float");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId", "AdditionId");

                    b.HasIndex("AdditionId");

                    b.ToTable("Variants_Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AdditionId = 9,
                            OriginalPrice = 6.9900000000000002,
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            AdditionId = 6,
                            OriginalPrice = 20.0,
                            Price = 20.0
                        },
                        new
                        {
                            ProductId = 2,
                            AdditionId = 7,
                            Price = 24.0
                        },
                        new
                        {
                            ProductId = 2,
                            AdditionId = 8,
                            Price = 24.0
                        },
                        new
                        {
                            ProductId = 3,
                            AdditionId = 1,
                            OriginalPrice = 17.0,
                            Price = 17.0
                        },
                        new
                        {
                            ProductId = 3,
                            AdditionId = 2,
                            Price = 20.399999999999999
                        },
                        new
                        {
                            ProductId = 3,
                            AdditionId = 3,
                            Price = 20.399999999999999
                        },
                        new
                        {
                            ProductId = 3,
                            AdditionId = 4,
                            Price = 20.399999999999999
                        },
                        new
                        {
                            ProductId = 3,
                            AdditionId = 5,
                            Price = 20.399999999999999
                        },
                        new
                        {
                            ProductId = 4,
                            AdditionId = 9,
                            OriginalPrice = 9.9900000000000002,
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            ProductId = 5,
                            AdditionId = 1,
                            OriginalPrice = 27.0,
                            Price = 27.0
                        },
                        new
                        {
                            ProductId = 5,
                            AdditionId = 2,
                            Price = 32.399999999999999
                        },
                        new
                        {
                            ProductId = 5,
                            AdditionId = 3,
                            Price = 32.399999999999999
                        },
                        new
                        {
                            ProductId = 5,
                            AdditionId = 4,
                            Price = 32.399999999999999
                        },
                        new
                        {
                            ProductId = 5,
                            AdditionId = 5,
                            Price = 32.399999999999999
                        },
                        new
                        {
                            ProductId = 6,
                            AdditionId = 9,
                            OriginalPrice = 349.99000000000001,
                            Price = 349.99000000000001
                        },
                        new
                        {
                            ProductId = 7,
                            AdditionId = 1,
                            OriginalPrice = 69.989999999999995,
                            Price = 69.989999999999995
                        },
                        new
                        {
                            ProductId = 7,
                            AdditionId = 2,
                            Price = 83.988
                        },
                        new
                        {
                            ProductId = 7,
                            AdditionId = 3,
                            Price = 83.988
                        },
                        new
                        {
                            ProductId = 7,
                            AdditionId = 4,
                            Price = 83.988
                        },
                        new
                        {
                            ProductId = 7,
                            AdditionId = 5,
                            Price = 83.988
                        },
                        new
                        {
                            ProductId = 8,
                            AdditionId = 9,
                            OriginalPrice = 3.9900000000000002,
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            ProductId = 9,
                            AdditionId = 1,
                            OriginalPrice = 2.0,
                            Price = 2.0
                        },
                        new
                        {
                            ProductId = 9,
                            AdditionId = 2,
                            Price = 2.3999999999999999
                        },
                        new
                        {
                            ProductId = 9,
                            AdditionId = 3,
                            Price = 2.3999999999999999
                        },
                        new
                        {
                            ProductId = 9,
                            AdditionId = 4,
                            Price = 2.3999999999999999
                        },
                        new
                        {
                            ProductId = 9,
                            AdditionId = 5,
                            Price = 2.3999999999999999
                        },
                        new
                        {
                            ProductId = 10,
                            AdditionId = 1,
                            OriginalPrice = 3.0,
                            Price = 3.0
                        },
                        new
                        {
                            ProductId = 10,
                            AdditionId = 2,
                            Price = 3.6000000000000001
                        },
                        new
                        {
                            ProductId = 10,
                            AdditionId = 3,
                            Price = 3.6000000000000001
                        },
                        new
                        {
                            ProductId = 10,
                            AdditionId = 4,
                            Price = 3.6000000000000001
                        },
                        new
                        {
                            ProductId = 10,
                            AdditionId = 5,
                            Price = 3.6000000000000001
                        });
                });

            modelBuilder.Entity("Handball_Shopv1.Shared.Variants_Product", b =>
                {
                    b.HasOne("Handball_Shopv1.Shared.Platform", "Addition")
                        .WithMany()
                        .HasForeignKey("AdditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Handball_Shopv1.Shared.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Handball_Shopv1.Shared.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
